obj-m		+= iop-memory.o
obj-y		+= iop-registers.o
obj-y		+= irq.o
obj-y		+= dmac-irq.o
obj-y		+= intc-irq.o
obj-y		+= scmd.o
obj-y		+= setup.o
obj-m		+= sif.o
obj-y		+= time.o

obj-$(CONFIG_PS2_GS)	+= gs.o gs-registers.o gs-irq.o gs-sysfs.o gif.o
obj-$(CONFIG_PS2_IOP)	+= iop.o
