obj-y		+= cdvd.o
obj-y		+= dma.o
obj-m		+= iop-memory.o
obj-y		+= iop-registers.o
obj-y		+= irq.o
obj-y		+= prom.o
obj-y		+= rtc.o
obj-y		+= setup.o
obj-m		+= sif.o
obj-y		+= time.o

obj-y		+= cache.o

obj-$(CONFIG_PS2_GS)	+= gs.o
obj-$(CONFIG_PS2_IOP)	+= iop.o
