obj-$(CONFIG_PS2_ETHER_SMAP)	+= smap.o smap_mdio.o
obj-$(CONFIG_PS2_ETHER_SMAPRPC)	+= smaprpc.o smaprpc_mdio.o
obj-$(CONFIG_PS2_PAD)		+= pad.o
obj-$(CONFIG_PS2_JOYSTICK)	+= joystick.o
obj-$(CONFIG_PS2_IOP_FIO)	+= iop-fio.o
obj-m				+= iop-dev9.o
obj-m				+= iop-module.o
