ps2smap-objs			:= smap.o smap_mdio.o
ps2smaprpc-objs				:= smaprpc.o smaprpc_mdio.o

obj-$(CONFIG_PS2_ETHER_SMAP)	+= ps2smap.o
obj-$(CONFIG_PS2_ETHER_SMAPRPC)	+= ps2smaprpc.o
obj-$(CONFIG_SONY_PS2)			+= sysproc.o
